alias rmf='rm -rf'
alias mkdir='mkdir -p'
alias c='clear'
alias cc='cd && clear'
alias la='ls -lhA'
alias ll='ls -A1'
alias df='df -h'
alias free='free -h'
alias cal='cal -m'
alias feh='feh -.'
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
