alias ..='cd ..'
alias ...="cd ../.."
alias rmf='rm -rf'
alias mkdir='mkdir -p'
alias c='clear'
alias cc='cd && clear'
alias la='ls -lhA'
alias ll='ls -A1'
alias df='df -h'
alias free='free -h'
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# git
alias depp='git'
alias gst='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git checkout'
alias gcam='git commit -a -m'
alias gcmsg='git commit -m'
alias gcl='git clone'
alias gcd='git checkout development'
alias gcm='git checkout master'
alias gd='git diff'
alias gm='git merge'
alias gpull='git pull'
alias gpush='git push'
